---
platform: "linux"
image: "docker:///dpb587/ravelry-api-php-default"
inputs:
  - name: "repository"
run:
  path: "repository/ci/tasks/run-tests/run.sh"
params:
  COMPOSER_GITHUB_TOKEN: optional
  RAVELRY_TEST_ACCESS_KEY: required
  RAVELRY_TEST_SECRET_KEY: required
  RAVELRY_TEST_ACCESS_TOKEN: required
  RAVELRY_TEST_ACCESS_TOKEN_SECRET: required
